name: chatgpt-telegram-workers
services:
  chatgpt-telegram-workers:
    image: ghcr.io/ibelieve3212/chatgpt-telegram-workers:latest
    # build: . # 如需本地构建取消注释
    ports:
      - "8787:8787"
    volumes:
      - ./config.json:/app/config.json:ro # change `./config.json` to your local path
      - ./wrangler.toml:/app/wrangler.toml:ro # change `./wrangler.toml` to your local path
    network_mode: "host" # If you access the proxy port based on the host